version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: wilden1-
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: warehouse
    ports:
      - "3306:3306"


  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
